deepspeed train.py \
    --deepspeed ./zero2.json \
    --model_name_or_path /data/yh/bigscience_bloom-1b1 \
    --data_path /data/yh/WuDaoCorpus2.0_base_200G \
    --data_num_limit 60 \
    --data_proc_num 40 \
    --bf16 True \
    --output_dir output_dir \
    --num_train_epochs 3 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 3 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to tensorboard \
    --use_streaming True\
    --max_steps 10000